send:
  body: [position, quaternion]
  joint_1D: [joint_position]
  joint_3D: [joint_quaternion]

receive:
  sphere: [position, quaternion]
  cylinder: [position, quaternion]
  # slider: [position, quaternion]